version: "3.9"

services:
  django:
    build: .
    container_name: django
    command: gunicorn --bind 0.0.0.0:8000 root.wsgi
    # We use 'expose' (internal) instead of 'ports' to avoid port conflicts
    expose:
      - "8000"
    volumes:
      - .:/app        # For local dev convenience (optional)
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=edu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx
    # Nginx listens on container port 80 -> host port 80
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
