version: "3.9"

services:
  django:
    build: .
    container_name: django
    command: gunicorn --bind 0.0.0.0:8000 root.wsgi
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=edu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
  postgres_data:
